export const studentListFilterData: any[] = [
  // 报读校区
  // {
  //   label: '报读校区',
  //   key: 'schoolIds',
  //   type: 'select',
  //   filter: true,
  //   remote: false,
  //   priority: 1,
  //   remoteUrl: '/api2/User/GetUserSchools',
  //   labelKey: 'schoolName',
  //   valueKey: 'id',
  //   mutiple: true,
  //   father: '',
  //   son: '',
  //   list: [],
  // },
  {
    label: '收支类型',
    key: 'inOutType',
    type: 'select',
    filter: false,
    remote: false,
    priority: 1,
    remoteUrl: '',
    mutiple: false,
    maxSpan: 7,
    father: '',
    son: ['s1', 's2', 's3', 's4'],
    list: [
      { value: '1', label: '订单收入', son: 's1' },
      { value: '2', label: '订单支出', son: 's2' },
      { value: '3', label: '其它收入', son: 's3' },
      { value: '4', label: '其它支出', son: 's4' },
    ],
  },
  {
    label: '收支小类',
    key: 's1',
    type: 'select',
    filter: false,
    remote: false,
    priority: 1,
    remoteUrl: '',
    mutiple: false,
    father: 'inOutType',
    son: '',
    list: [
      { value: 1, label: '报名收费' },
      { value: 2, label: '预存余额' },
      { value: 6, label: '补费' },
      { value: 3, label: '转课补差额' },
      { value: 4, label: '复课收费' },
      { value: 5, label: '教材杂费收费' },
    ],
  },
  {
    label: '收支小类',
    key: 's2',
    type: 'select',
    filter: false,
    remote: false,
    priority: 1,
    remoteUrl: '',
    mutiple: false,
    father: 'inOutType',
    son: '',
    list: [
      { value: 100, label: '退学费' },
      { value: 101, label: '退余额' },
      { value: 102, label: '转课退差额' },
      { value: 103, label: '退教材杂费' },
    ],
  },
  {
    label: '收支小类',
    key: 's3',
    type: 'select',
    filter: true,
    remote: false,
    priority: 1,
    remoteUrl: '',
    mutiple: false,
    father: 'inOutType',
    son: '',
    list: [],
  },
  {
    label: '收支小类',
    key: 's4',
    type: 'select',
    filter: true,
    remote: false,
    priority: 1,
    remoteUrl: '',
    mutiple: false,
    father: 'inOutType',
    son: '',
    list: [],
  },
  //   // 课程大类/报读课程
  //   {
  //     label: '课程大类',
  //     key: 'lessonClassId',
  //     type: 'select',
  //     filter: true,
  //     remote: true,
  //     priority: 1,
  //     remoteUrl: '/api2/Lesson/GetLessonClassData',
  //     labelKey: 'lessonClassName',
  //     valueKey: 'id',
  //     mutiple: true,
  //     father: '',
  //     son: 'lessonId',
  //     list: [],
  //   },
  //   {
  //     label: '报读课程',
  //     key: 'lessonId',
  //     type: 'select',
  //     filter: true,
  //     remote: true,
  //     priority: 1,
  //     remoteUrl: '/api2/Lesson/Query',
  //     labelKey: 'lessonName',
  //     valueKey: 'lessonId',
  //     mutiple: true,
  //     father: 'lessonClassId',
  //     son: '',
  //     list: [],
  //   },
  // “学管师”筛选项需要根据是否开启了学管师自定义字段动态生成
  // {
  //   label: '学管师',
  //   key: 'educationConsultantHrdocIds',
  //   type: 'select',
  //   filter: true,
  //   remote: true,
  //   priority: 1,
  //   remoteUrl: '/api2/Org/GetEducationConsultantHrdocList',
  //   labelKey: 'educationConsultantHrdocName',
  //   valueKey: 'educationConsultantHrdocId',
  //   mutiple: true,
  //   father: '',
  //   son: '',
  //   list: []
  // },
  // 授课模式
  {
    label: '授课模式',
    key: 'mode',
    type: 'select',
    filter: false,
    remote: false,
    priority: 2,
    remoteUrl: '',
    mutiple: false,
    father: '',
    son: '',
    list: [
      {
        label: '一对一',
        value: '2',
      },
      {
        label: '班课',
        value: '1',
      },
    ],
  },
  // 收费模式
  //   {
  //     label: '收费模式',
  //     key: 'classTimeType',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 1,
  //     remoteUrl: '',
  //     mutiple: false,
  //     maxSpan: 7,
  //     father: '',
  //     son: ['classtime', 'time'],
  //     list: [
  //       { label: '按课时（剩余课时）', value: 2, son: 'classtime' },
  //       { label: '按期（剩余课时）', value: 1, son: 'classtime' },
  //       { label: '按时间（到期时间）', value: 3, son: 'time' },
  //       { label: '按课时（课时有效期）', value: 4, son: 'time' },
  //     ],
  //   },
  //   {
  //     label: '剩余情况',
  //     key: 'classtime',
  //     type: 'numberrange',
  //     filter: false,
  //     remote: false,
  //     priority: 1,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: 'classTimeType',
  //     son: '',
  //     unit: '课时',
  //     list: [],
  //     range: [-9999, 9999],
  //   },
  //   {
  //     label: '剩余情况',
  //     key: 'time',
  //     type: 'daterange',
  //     filter: false,
  //     remote: false,
  //     priority: 1,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: 'classTimeType',
  //     son: '',
  //     list: [],
  //   },
  // 课程状态
  //   {
  //     label: '报读状态',
  //     key: 'status',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 1,
  //     remoteUrl: '',
  //     mutiple: true,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '在读',
  //         value: '1',
  //       },
  //       {
  //         label: '转课',
  //         value: '2',
  //       },
  //       {
  //         label: '退费',
  //         value: '3',
  //       },
  //       {
  //         label: '停课',
  //         value: '4',
  //       },
  //       {
  //         label: '结课',
  //         value: '5',
  //       },
  //     ],
  //   },
  //   // 扩展属性---筛选项（默认不显示）
  //   // 是否消超
  //   {
  //     label: '是否消超',
  //     key: 'isExcessConsumption',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '是',
  //         value: '1',
  //       },
  //       {
  //         label: '否',
  //         value: '0',
  //       },
  //     ],
  //   },
  //   // 是否升期
  //   {
  //     label: '是否升期',
  //     key: 'isUp',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '是',
  //         value: '1',
  //       },
  //       {
  //         label: '否',
  //         value: '0',
  //       },
  //     ],
  //   },
  //   // 是否分班
  //   {
  //     label: '是否分班',
  //     key: 'isDivideIntoClasses',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '是',
  //         value: '1',
  //       },
  //       {
  //         label: '否',
  //         value: '0',
  //       },
  //     ],
  //   },
  //   // 是否欠费
  //   {
  //     label: '是否欠费',
  //     key: 'isArrearage',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '是',
  //         value: '1',
  //       },
  //       {
  //         label: '否',
  //         value: '0',
  //       },
  //     ],
  //   },
  //   {
  //     label: '最近上课时间',
  //     key: 'classDate',
  //     type: 'daterange',
  //     filter: false,
  //     remote: true,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: true,
  //     father: '',
  //     son: '',
  //   },
  //   {
  //     label: '报名日期',
  //     key: 'enrollAt',
  //     type: 'daterange',
  //     filter: false,
  //     remote: true,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: true,
  //     father: '',
  //     son: '',
  //   },
  //   {
  //     label: '停课日期',
  //     key: 'suspendClassDate',
  //     type: 'daterange',
  //     filter: false,
  //     remote: true,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: true,
  //     father: '',
  //     son: '',
  //   },
  //   {
  //     label: '结课日期',
  //     key: 'endClassDate',
  //     type: 'daterange',
  //     filter: false,
  //     remote: true,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: true,
  //     father: '',
  //     son: '',
  //   },
  //   {
  //     label: '是否有已失效课时',
  //     key: 'invalidClassTimes',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '是',
  //         value: '1',
  //       },
  //       {
  //         label: '否',
  //         value: '0',
  //       },
  //     ],
  //   },
  //   {
  //     label: '在读课程数',
  //     key: 'lessonCount',
  //     type: 'numberrange',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     range: [0, 9999],
  //     fixed: 0,
  //     list: [],
  //   },
  //   // 类型新老生
  //   {
  //     label: '新老生',
  //     key: 'newStuinfo',
  //     type: 'select',
  //     filter: false,
  //     remote: false,
  //     priority: 2,
  //     remoteUrl: '',
  //     mutiple: false,
  //     father: '',
  //     son: '',
  //     list: [
  //       {
  //         label: '新生',
  //         value: '1',
  //       },
  //       {
  //         label: '老生',
  //         value: '0',
  //       },
  //     ],
  //   },
];
